[package]
name = "minarch"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }
render = { workspace = true }
libloading = { workspace = true }
flate2 = { workspace = true }

platform-tg5040 = { workspace = true, optional = true }

[features]
default = []
platform-tg5040 = ["dep:platform-tg5040"]
